### ISSUE TITLE
Python developer experience

### ISSUE THREAD

**Issue by HeyItsBATMAN** [IIIF-Commons/iiif_3d_blender_plugin#13]
Since I could not attend the initial meeting, I'm not sure if you already shared your thoughts on this, but since we may all be using different code editors and are used to different setups, I am wondering how we should handle things like linting, type hints, formatting, etc..

For creating the first PR with code (https://github.com/IIIF-Commons/3d-blender-plugin/pull/12), I locally already used some tools, but skipped on adding anything related to them inside of the commit.

Those tools are:
- pyenv for enforcing a specific Python version (in this case 3.12)
- creating a virtual environment in the root directory of the project
- adding [fake-bpy-module](https://pypi.org/project/fake-bpy-module-4.2/) as a dependency for being able to lint and use type hints with the Blender Python API
- using [pyright](https://github.com/microsoft/pyright) for type checking and [ruff](https://github.com/astral-sh/ruff) for linting and formatting

I do not have any strong opinion on any of any of these niceties for development of this plugin.
If needed, I can share my necessary configuration for this.

**Comment by glenrobson** [comment]
Group agreed pull request would be useful. 

Good with including fake-bpy-module

Some discussion on pyright but will happy to give it a go.

For info iiif-prezi uses a different linting: https://github.com/iiif-prezi/iiif-prezi3
